[tox]
requires =
    tox>=4.2
env_list =
    py{313, 312, 311, 310}

[testenv]
deps =
    allianceauth
    django-webtest
    factory_boy
    pytest
    pytest-cov
    pytest-django
set_env =
    DJANGO_SETTINGS_MODULE = testauth.settings.local
commands =
    pytest --cov=aa_kanban --cov-report=xml --cov-report=html
install_command = python -m pip install -U {opts} {packages}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
