# Generated by Django 5.2.17 on 2026-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_kanban', '0002_kanbangroup_alter_board_view_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_creation_webhook', models.URLField(blank=True, help_text='Discord Webhook URL for global board creation notifications.', null=True)),
            ],
            options={
                'verbose_name': 'Kanban Setting',
                'verbose_name_plural': 'Kanban Settings',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='discord_webhook_cards',
            field=models.URLField(blank=True, help_text='Discord Webhook URL for card movement notifications on this board.', null=True),
        ),
    ]
