# Generated by Django 5.2.17 on 2026-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_kanban', '0003_kanbansetting_board_discord_webhook_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional context for this column'),
        ),
        migrations.AddField(
            model_name='list',
            name='wip_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum cards (0 for unlimited)'),
        ),
    ]
