# Generated by Django 5.2.17 on 2026-09-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_kanban', '0005_alter_label_unique_together_alter_label_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbansetting',
            name='ticket_board',
            field=models.ForeignKey(blank=True, help_text='Board where member tickets will be created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='aa_kanban.board'),
        ),
    ]
