# Generated by Django 5.2.17 on 2026-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_kanban', '0006_kanbansetting_ticket_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbansetting',
            name='ticket_board',
        ),
        migrations.AddField(
            model_name='kanbansetting',
            name='ticket_boards',
            field=models.ManyToManyField(blank=True, help_text='Boards where member tickets can be created.', related_name='+', to='aa_kanban.board'),
        ),
    ]
