# Generated by Django 5.2.17 on 2026-09-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_kanban', '0009_kanbangroup_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='assigned_group',
            field=models.ForeignKey(blank=True, help_text='Target team/group for this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='aa_kanban.kanbangroup'),
        ),
        migrations.AddField(
            model_name='card',
            name='discord_thread_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the associated Discord Thread', null=True),
        ),
    ]
