# Generated by Django 5.2.17 on 2026-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_kanban", "0010_card_assigned_group_card_discord_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanbansetting",
            name="ticket_channel_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Discord Channel ID where ticket threads will be created.",
                null=True,
            ),
        ),
    ]
