# Generated by Django 5.2.17 on 2026-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_kanban', '0013_remove_card_assigned_group_kanbanteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='discord_ticket_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Discord Channel ID where ticket threads will be created for this board.', null=True),
        ),
    ]
