# Generated by Django 5.2.17 on 2026-09-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_kanban", "0014_board_discord_ticket_channel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kanbansetting",
            name="ticket_boards",
        ),
        migrations.AddField(
            model_name="board",
            name="is_ticket_board",
            field=models.BooleanField(
                default=False,
                help_text="Allow members to submit tickets to this board.",
            ),
        ),
    ]
