# Generated by Django 5.2.17 on 2026-09-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_kanban', '0015_remove_kanbansetting_ticket_boards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanteam',
            name='ticket_board',
            field=models.ForeignKey(blank=True, help_text='The Kanban board where tickets for this team will be created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='aa_kanban.board'),
        ),
    ]
