# Generated by Django 5.2.17 on 2026-09-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_kanban", "0016_kanbanteam_ticket_board"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kanbansetting",
            name="ticket_channel_id",
        ),
    ]
